[build]
publish = "dist"
ignore = "requirements.txt"
command = "npm run build"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[context]
[context.production]
command = "echo 'Static site - no build needed'"

[context.deploy-preview]
command = "echo 'Static site - no build needed'"