[build]
  # No build command needed for static HTML
  publish = "."
  ignore = "requirements.txt"

[build.environment]
  # Explicitly set as static site
  NODE_VERSION = "18"

[[redirects]]
  # Redirect all routes to index.html for SPA behavior
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  # Production-specific settings
  command = "echo 'Static site - no build needed'"

[context.deploy-preview]
  # Deploy preview settings
  command = "echo 'Static site - no build needed'" 